### ISSUE TITLE
Repacking archives

### ISSUE THREAD

**Issue by imKota** [Azukee/Macaron#17]
Do you plan to add repacking * .pfs?

**Comment by HoLLy-HaCKeR** [comment]
Not for the moment, perhaps in the future. @Azukee?

**Comment by Azukee** [comment]
Repacking has been on my mind recently but I don't think it'll fit in the spectrum for Macaron.
I feel like dedicating Macaron only to unpacking at the moment.
Maybe there'll be a counterpart project in the future?

If you don't have any more questions feel free to close this issue

**Comment by HoLLy-HaCKeR** [comment]
We can always add an interface that allows for repacking (IPacker or something), so we can make only some archive formats repackable. I may look into it in the future so I'll keep this open, but it's gonna be pretty hard for some.

**Comment by imKota** [comment]
@HoLLy-HaCKeR @Azukee
I just want to translate the novel into another language, but I have problems with repacking.
I think this will help you.
https://github.com/morkt/GARbro/blob/12bbd3a3/ArcFormats/Artemis/ArcPFS.cs#L101

Thanks for the answers, I will wait:3

**Comment by vnlovers** [comment]
You don't have to repack your files for Artemis engine. Put your files in your game, and it will read translation automatically.

**Comment by tung12343** [comment]
> You don't have to repack your files for Artemis engine. Put your files in your game, and it will read translation automatically.

could you specify what file really, the whole folder or?  (sorry for being an idiot)
